### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by SpaceLeft** [VitalDevelopment/VitalList#14]
don't talk about copyright you already copy from vcodes

**Comment by markawes** [comment]
What?

**Comment by sldless** [comment]
What do you mean by copy? 
We didn't copy anything from vcodes as am aware of.

**Comment by BrydenIsNotSmart** [comment]
Can you please tell us what code we copied?

**Comment by EliteNover** [comment]
says the guy who forks other peoples githubs of discord bots, +1 for bozo

**Comment by markawes** [comment]
> says the guy who forks other peoples githubs of discord bots, +1 for bozo

Dude can you stop being a dick and just let us know what you think has been copied so that the situation can be addressed.

There is no need to be a little bitch about it.

**Comment by clqu** [comment]
He's trying to say you stole my code and removed our name. You smart people can't even write 2 grams of code, I congratulate you with your empty head.  https://github.com/vcodes-xyz/benedict

**Comment by BrydenIsNotSmart** [comment]
What code did we copy is what I'm trying to figure out?

**Comment by clqu** [comment]
I should have believed it when I saw from his name that he wasn't smart. This code is all mine, I don't know who you're trying to fool, but Void Development is a registered company. You better remove the repo before we do anything.

**Comment by BrydenIsNotSmart** [comment]
This code isn't yours.

**Comment by clqu** [comment]
> don't talk about copyright you already copy from vcodes

it's not ours, thanks anyway for defending our rights.

**Comment by BrydenIsNotSmart** [comment]
Issue resolved + issue opener never responded
