### ISSUE TITLE
🔍 Code Review 

### ISSUE THREAD

**Issue by Elara-Discord-Bots** [VitalDevelopment/VitalList#9]
- You have `req, req, next` when it should be `req, res, next`
> https://github.com/VitalDevelopment/VitalList/blob/master/src/app.js#L1749

- Using an unneeded `await` here: 
> https://github.com/VitalDevelopment/VitalList/blob/master/src/app.js#L1676
> https://github.com/VitalDevelopment/VitalList/blob/master/src/app.js#L1544

- Using local imports for models (defining per-request)
> These should be a global variable to improve the code 

- Defining `Array.shuffle`  multiple types per-request 
> This should be define once at the top or bottom of the file (since it's attaching itself to the global Array)

- Not doing any error catching for the endpoints (which can and will cause an Internal Server Error and the page will fail to load for the user)

- Instead of fetching the bot/server's info every single request perhaps just store the details you need and have a cron schedule to update the info in the database. (it would be better for everything and heavily improve latency)

- Having both `/me` and `/users/:id` endpoints is pointless. Just combine them into one (ex: `/users/@me` or `/users/me`)

- Double fetching the server database entry: https://github.com/VitalDevelopment/VitalList/blob/master/src/app.js#L1032 (this should just use the `server` const already defined)

- The `/api/bots/:id` won't return the correct data: 
> https://github.com/VitalDevelopment/VitalList/blob/master/src/app.js#L870

It should be changed to:
```js
res.json(data)
```

- As the list gets bigger stuff like this: 
https://github.com/VitalDevelopment/VitalList/blob/master/src/app.js#L203
will cause issues and should most likely be handled by a cron job instead of doing it per-request 

- Double fetching the database for approved and denied bots: 
https://github.com/VitalDevelopment/VitalList/blob/master/src/app.js#L199
This will cause more latency issues and just spam the database 

- Adding users to a server without consent from the user goes against Developer ToS 
https://github.com/VitalDevelopment/VitalList/blob/master/src/app.js#L159

- The `app` variable is being defined twice: 
https://github.com/VitalDevelopment/VitalList/blob/master/src/app.js#L19
https://github.com/VitalDevelopment/VitalList/blob/master/src/app.js#L35

### Just a recommendation 
Get `eslint` and use it 🙃
-------

You can thank @markawes for a review lol

**Comment by BrydenIsNotSmart** [comment]
Thank you for the feedback, we are currently working to fix theses issues.
